apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: es
  labels:
    app: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
        ports:
          - containerPort: 9200
            name: elasticsearch
        volumeMounts:
          - name:  elasticsearch-persistent-storage
            mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elasticsearch-persistent-storage
          persistentVolumeClaim:
            claimName: es-pv-claim