apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: es
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    name: elasticsearch
  type: NodePort